### PR TITLE
Fix registration

### PR DESCRIPTION
**Pull request by akeym**
Fixes creation of new registrations by adding necessary values to API requests.

### CODE REVIEW

**Comment by akeym** [comment]
@zeeman  or @drkitty

**Comment by zeeman** [comment]
Is this the last error you were getting?

```
[Mon Mar 23 18:22:44 2015] [error] API request failed
[Mon Mar 23 18:22:44 2015] [error]     https://cyder.oregonstate.edu/api/v1/core/system/
[Mon Mar 23 18:22:44 2015] [error]     {"name": "public-efc08fb48a4d7f990f60fb1dfed2f6e6-Wireless"}
[Mon Mar 23 18:22:44 2015] [error]     {"ctnr": ["This field is required."]}
```

**Comment by drkitty** [comment]
Looks like I already fixed this but then I forgot to push it to the main repo. I just pushed the fix (along with a couple other things).

**Comment by drkitty** [comment]
**Resolved by some commit a long time ago.**

**Pull request closed without merging**
